### PR TITLE
(#4518) Returning 404 error if event ID does not exist.

### LINKED ISSUE #4518: Error 503 when downloading .ICS file for non-existent event.
### Issue description
A status 503 error occurs when attempting to download the `.ics` file for an event which has been deleted or otherwise has an invalid URL.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1. Find a non-existent node ID (`123` seems a good bet).
2. Browse to `https://sbir-dev-acsf.cancer.gov/node/123/icalendar` (Any of the top-level sites should work).

### What's the expected result?
- A status 404 response.

### What's the actual result?
- A status 503 response with a "Temporarily Unavailable" message from Akamai.

### Additional details / screenshot
- Running in a local development environment returns this message to the user. (tl;dr, Drupal doesn't like that `ICalendarController::download` returns `FALSE` instead of something derived from `Symfony\Component\HttpFoundation\Response` [when the node isn't found](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/modules/custom/cgov_event/src/Controller/ICalendarController.php#L90-L93).)
```
The website encountered an unexpected error. Try again later.

Symfony\Component\HttpKernel\Exception\ControllerDoesNotReturnResponseException: The controller must return a "Symfony\Component\HttpFoundation\Response" object but it returned a boolean value (false). in () (line 98 of core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php).
Symfony\Component\HttpKernel\HttpKernel->handleRaw() (Line: 76)
Symfony\Component\HttpKernel\HttpKernel->handle() (Line: 58)
Drupal\Core\StackMiddleware\Session->handle() (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle() (Line: 28)
Drupal\Core\StackMiddleware\ContentLength->handle() (Line: 191)
Drupal\page_cache\StackMiddleware\PageCache->fetch() (Line: 128)
Drupal\page_cache\StackMiddleware\PageCache->lookup() (Line: 82)
Drupal\page_cache\StackMiddleware\PageCache->handle() (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle() (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle() (Line: 36)
Drupal\Core\StackMiddleware\AjaxPageState->handle() (Line: 51)
Drupal\Core\StackMiddleware\StackedHttpKernel->handle() (Line: 704)
Drupal\Core\DrupalKernel->handle() (Line: 19)
```
- This is very similar, but not identical, to #4392; that scenario functions correctly in the `-cms` site.

### Related Links

- [Datadog issue](https://app.ddog-gov.com/error-tracking?query=&fromUser=true&issueId=558a8fe4-d445-11ef-841a-da7ad0900007&refresh_mode=sliding&source=backend&from_ts=1736902941523&to_ts=1737507741523&live=true) (probably)

### LINKED ISSUE #4546: cgov_event ICalendarController throws deprecated 500 error
### Issue description
```
php: Deprecated function: Return type of Eluceo\iCal\PropertyBag::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in include() (line 14 of /mnt/www/html/ncigov01live/vendor/eluceo/ical/src/PropertyBag.php) 
```

Thoe source appears to be this line:

https://github.com/NCIOCPL/cgov-digital-platform/blob/40773e68b8664aaa277d2e3c66c20828c0e4af5e/docroot/profiles/custom/cgov_site/modules/custom/cgov_event/src/Controller/ICalendarController.php#L134

```
#0 /mnt/www/html/ncigov01live/docroot/core/includes/bootstrap.inc(166): _drupal_error_handler_real(8192, 'Return type of ...', '/mnt/www/html/n...', 73)
#1 /mnt/www/html/ncigov01live/vendor/eluceo/ical/src/PropertyBag.php(14): _drupal_error_handler(8192, 'Return type of ...', '/mnt/www/html/n...', 73)
#2 /mnt/www/html/ncigov01live/vendor/composer/ClassLoader.php(576): include('/mnt/www/html/n...')
#3 /mnt/www/html/ncigov01live/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/mnt/www/html/n...')
#4 /mnt/www/html/ncigov01live/vendor/eluceo/ical/src/Component/Calendar.php(247): Composer\Autoload\ClassLoader->loadClass('Eluceo\\iCal\\Pro...')
#5 /mnt/www/html/ncigov01live/vendor/eluceo/ical/src/Component.php(97): Eluceo\iCal\Component\Calendar->buildPropertyBag()
#6 /mnt/www/html/ncigov01live/vendor/eluceo/ical/src/Component.php(125): Eluceo\iCal\Component->build()
#7 /mnt/www/html/ncigov01live/docroot/profiles/custom/cgov_site/modules/custom/cgov_event/src/Controller/ICalendarController.php(134): Eluceo\iCal\Component->render()
#8 [internal function]: Drupal\cgov_event\Controller\ICalendarController->download('1116')
#9 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#10 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/Render/Renderer.php(638): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#11 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#12 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#13 /mnt/www/html/ncigov01live/vendor/symfony/http-kernel/HttpKernel.php(181): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#14 /mnt/www/html/ncigov01live/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#15 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(53): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#17 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/StackMiddleware/ContentLength.php(28): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#18 /mnt/www/html/ncigov01live/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(191): Drupal\Core\StackMiddleware\ContentLength->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#19 /mnt/www/html/ncigov01live/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(128): Drupal\page_cache\StackMiddleware\PageCache->fetch(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#20 /mnt/www/html/ncigov01live/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(82): Drupal\page_cache\StackMiddleware\PageCache->lookup(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#21 /mnt/www/html/ncigov01live/docroot/modules/contrib/shield/src/ShieldMiddleware.php(263): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#22 /mnt/www/html/ncigov01live/docroot/modules/contrib/shield/src/ShieldMiddleware.php(130): Drupal\shield\ShieldMiddleware->bypass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#23 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\shield\ShieldMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#24 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#25 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/StackMiddleware/AjaxPageState.php(36): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#26 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/StackMiddleware/StackedHttpKernel.php(51): Drupal\Core\StackMiddleware\AjaxPageState->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#27 /mnt/www/html/ncigov01live/docroot/core/lib/Drupal/Core/DrupalKernel.php(741): Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#28 /mnt/www/html/ncigov01live/docroot/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#29 {main}.
```

> **ESTIMATE** TBD

### Steps to reproduce the issue

1. Login to `www-dev-ac` as a user with `site_admin` privilleges.
2. Browse to `https://www-dev-ac.cancer.gov/admin/reports/dblog` and note the most recent log entry.
3. Download `https://www-dev-ac.cancer.gov/node/1836/icalendar` (or any other event's `.ics`)
4. Reload the log

### What's the expected result?
- No new messages.

### What's the actual result?
- A warning about the deprecated function.

### Additional details / screenshot
- [Datadog issue](https://app.ddog-gov.com/logs?query=issue.id%3A1752965c-d21c-11ef-ad01-da7ad0900007&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1736838000000&to_ts=1737050880000&live=false)

### Related Tickets
* Issue #3903 (another issue with the same functionality)

### PR DESCRIPTION
**Pull request by navsunka**
Closes #4518
Closes #4546

### CODE REVIEW

**Review by blairlearn — APPROVED** [review]

File: docroot/profiles/custom/cgov_site/modules/custom/cgov_event/src/Controller/ICalendarController.php [hunk 1]
```diff
@@ -89,7 +89,8 @@ public function download($nid) {
     // Load event node.
     $node = $this->entityTypeManager()->getStorage('node')->load($nid);
     if (empty($node)) {
```
Comment (bryanpizzillo) [inline docroot/profiles/custom/cgov_site/modules/custom/cgov_event/src/Controller/ICalendarController.php:91]: We should also check the bundle type. @bryanpizzillo will handle the change.

**Review by bryanpizzillo — CHANGES_REQUESTED** [review]
@bryanpizzillo will handle the updates here.

**Review by bryanpizzillo — APPROVED** [review]

**Comment by blairlearn** [comment]
Verified no errors when retrieving an `.ics` file (#4546)
