### PR TITLE
(#2008) Links are not being switched over on microsites.

### LINKED ISSUE #2008: Links are not being switched out on microsites
On the 3 microsites, links that are pointing to cancer.gov are not working. They are blank right now with no targets.

Examples include:
- http://ncigovcdode179.prod.acquia-sites.com/living/finished-treatment — the links under Coping 
- http://ncigovcdode179.prod.acquia-sites.com/rare-brain-spine-tumor/tumors/about-cns-tumors — in the "How are tumors monitored?" section, the "imaging procedures" link 
- http://ncigovcdode178.prod.acquia-sites.com/rare-tumors/rare-bone-tumors/chordoma — toward the bottom of the page, the "resources to help you understand cancer prognosis." link
- http://ncigovcdode178.prod.acquia-sites.com/pediatric-adult-rare-tumor/rare-tumors/rare-bone-tumors/adamantinoma, the "resources to help you understand cancer prognosis" link
- http://ncigovcdode178.prod.acquia-sites.com/pediatric-adult-rare-tumor/rare-tumors/rare-digestive-system-tumors/fibrolamellar-hepatocellular-carcinoma, the " resources to help you understand cancer prognosis" link

### PR DESCRIPTION
**Pull request by adriancofie**
Closes #2008 
Cross-site link replacement on micro-sites.

### CODE REVIEW

File: docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/src/Plugin/migrate/process/ReplaceLinks.php [hunk 1]
```diff
@@ -105,7 +105,9 @@ public function createLinkitEmbed($entity_id, $sys_siteid, $content, $anchor) {
       $url = $translationList[$entity_id]['url'];
       // See if it has an English translation.
       $translationid = $translationList[$entity_id]['translationid'];
-      if (!empty($translationid)) {
+
+      // Empty arrays have non-strict comparison, check is_null also.
+      if ($translationid != 'NULL' && !empty($translationid) && !is_null($translationid)) {
```
Comment (adriancofie) [inline docroot/profiles/custom/cgov_site/modules/custom/cgov_migration/src/Plugin/migrate/process/ReplaceLinks.php]: Main fix. NULL string in incoming data.
