### PR TITLE
Prototype/4641 spike content views drupal otb

### LINKED ISSUE #4641: Content & Media Views: Rebuild from OOB Drupal and Updates to Content, Content Moderation, Media, and Media Moderation views
This story started as a spike, but are transferring to a story as the changes completed during the course of the spike will be pushed to production. A summary of the changes made are as follows:

**Rebuild of Current Views Using Updated out of the Box Code from Drupal**
- Replaced our current content and media views with an updated Drupal OOB version. Updated columns to match production.
- Column order should still match production, though names have changed for some as described below.
- Other functionality should still work as it does in production (or in some cases like bulk operations not work)

**Changes to Column Names:** 
- "Author" column has been updated to be "Last Published by:" on the Content and Media views. The value shown in this column should match with the person who last published the page. (Previously this has just shown the initial creator of the page)
- "Author" column has been updated to be "Last Modified by:" on the moderation tab within Content and Media. This value should match the user who last modified the page while it was in a workflow state that appears in the content moderation or media moderation views (ie: Editing for content or draft for media)
- The "Updated" column that appears on the Content and Media main tabs has been updated to say "Last Published:" and the date shown should reflect when the content was last published.
- The "Updated column that appears on the moderation tab within Content and Media has been updated to say "Last Modified:" and the date shown should reflect when the content was last modified.

**Updated Date/Time shown to consistently appear for English and Spanish** 
- The date format should now appear the same for both English and Spanish pages and that format should match the date format currently show in production for English - MM/DD/YYYY - HH:MM. (Previously it appeared in a different format for Spanish.)

===================

### Spike Overview
In order to start evaluating changes to the existing content report views in Drupal, we want to do a spike reverting the changes we've made over time to use the latest "out of the box" views from Drupal and evaluating.

### Expected Deliverables:
An ODE with the content view, content moderation view, and the media view reverted back to the Drupal Core.

Once the ODE is up, we can capture notes from a technical perspective about the changes/differences and also review/discuss with the Federal team. @welshja will help coordinate some review from the team and client to review/discuss.

### Additional Notes:
These are the three views from Drupal. Hopefully, these can be copied overtop of what is in our code base.

- Content: https://github.com/drupal/drupal/blob/10.4.3/core/modules/node/config/optional/views.view.content.yml
- Content Moderation: https://github.com/drupal/drupal/blob/10.4.5/core/modules/content_moderation/config/optional/views.view.moderated_content.yml
- Media: https://github.com/drupal/drupal/blob/10.4.5/core/modules/media/config/optional/views.view.media.yml

There are also a few known issues or enhancements requests that we should review to see if these changes would address (or make it easier to address). **The ODE for this spike should be build with the out-of-the-box Drupal code. Just noting these as something we can look as we review the OOB changes**

- https://github.com/NCIOCPL/cgov-digital-platform/issues/2380
- https://github.com/NCIOCPL/cgov-digital-platform/issues/4203
- Try to move operations column to the same position as it is in production currently on all 3 views
- Look into any existing Drupal modules that we may want to consider [this can wait until Joe is back if too vague or not a good use of time for Erik]
- Look into how to hide/show options in the Selected Item menu that appears at the bottom of the page when you select an item (black bar). Can use the two options to make something "sticky" to experiment with.

### Results of Spike
Erik was able to rebuild the views currently in production using a newer out-of-the-box version of these views from Drupal. This will help address a tech debt issue we have had where we had to update/patch around these views because the version we customized would not update without breaking.

Additionally, Erik was able to make some updates that help address outstanding bugs as well as improve labels across these views. 

Given all this, we want to proceed with what has been built to have QA conduct testing on ACSF with more real content to be tested against.

### Summary of Changes for QA Testing on ACSF:

- "Author" column has been updated to be "Last Published by:" on the Content and Media views. The value shown in this column should match with the person who last published the page. (Previously this has just shown the initial creator of the page)
- "Author" column has been updated to be "Last Modified by:" on the moderation tab within Content and Media. This value should match the user who last modified the page while it was in a workflow state that appears in the content moderation or media moderation views (ie: Editing for content or draft for media)
- The "Updated" column that appears on the Content and Media main tabs has been updated to say "Last Published:" and the date shown should reflect when the content was last published.
- The "Updated column that appears on the moderation tab within Content and Media has been updated to say "Last Modified:" and the date shown should reflect when the content was last modified.
- The date format should now appear the same for both English and Spanish pages and that format should match the date format currently show in production for English - MM/DD/YYYY - HH:MM. (Previously it appeared in a different format for Spanish.)
- Column order should still match production, though names have changed for some as described above.
- Other functionality should still work as it does in production (or in some cases like bulk operations not work)

### PR DESCRIPTION
**Pull request by erikscottmeyer**
Closes #4641

### CODE REVIEW

File: docroot/lib/CgovPlatform/Tests/CgovSchemaExclusions.php [hunk 1]
```diff
@@ -39,6 +39,10 @@ class CgovSchemaExclusions {
     // for the tracked issue.
     'adobe_dtm.settings',
     'views.view.samlauth_map',
+    'views.view.content',
```
Comment (bryanpizzillo) [inline docroot/lib/CgovPlatform/Tests/CgovSchemaExclusions.php:42]: Can you please add a comment for the specific error that you were getting? I forget what it was exactly, but it would be good if someone hits it in the future. (It was something to do with missing schema for settings for dates which should have broken for other uses...)

File: docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/core.date_format.cgov_short_date.yml [hunk 2]
```diff
@@ -0,0 +1,7 @@
+langcode: en
```
Comment (bryanpizzillo) [inline docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/core.date_format.cgov_short_date.yml:1]: Can this file be reverted if it is not needed anymore? I think it is left over from Blair's PR which was missing the timestamp.

File: docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/editor.editor.full_html.yml [hunk 3]
```diff
@@ -36,7 +36,7 @@ settings:
       - insert_block_content
       - cgov_featured_content_button
       - '|'
-      - 'glossifier'
+      - glossifier
```
Comment (bryanpizzillo) [inline docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/editor.editor.full_html.yml:39]: Was this from a `drush features:export cgov_core` ?

File: docroot/profiles/custom/cgov_site/translations/cgov_site.es.po [hunk 4]
```diff
@@ -14,6 +14,10 @@ msgctxt "PHP date format"
 msgid "F j, Y"
 msgstr "j \\d\\e F \\d\\e Y"
 
+msgctxt "PHP date format"
```
Comment (bryanpizzillo) [inline docroot/profiles/custom/cgov_site/translations/cgov_site.es.po:17]: This should be able to be reverted as well if `core.date_format.cgov_short_date is being reverted.

**Review by bryanpizzillo — CHANGES_REQUESTED** [review]
A couple of things leftover from the other approach for the English dates in the listing views.

File: docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/editor.editor.full_html.yml (hunk 3 above)
Comment (erikscottmeyer) [reply docroot/profiles/custom/cgov_site/modules/custom/cgov_core/config/install/editor.editor.full_html.yml:39]: yes

**Review by bryanpizzillo — APPROVED** [review]
