### PR TITLE
(#2236, #3804, #3807, #3966, #4054) Layout Builder for Blogs 

### LINKED ISSUE #2236: Blogs module - remove dead code
Remove `blog-topic-path` and all references from cgov_blog.tokens.inc and configuration files.

### LINKED ISSUE #3807: Replace Page Manager with Layout Builder for Blogs
Layout Builder is a core module used for complicated page layouts and was still being developed at the time we were building the digital platform. When we got to blogs in our development cycle we had to fall back to using Page Manager and Panels to handle the complicated layouts. Page Manager and Panels were two VERY popular Drupal 7 modules that had been ported to Drupal 8. The goal for Layout Builder was to have a core feature that handles the basic use cases of Page Manager and Panels. Now that Layout Builder has been out for a while, Page Manager is getting long in the tooth. The biggest issue with Page Manager is that it is not integrated with core - such as the problem with the `latest` route in #3804. Additionally, it may be the cause of the issue in #3806. Page Manager was never to be a long term solution for handling the complicated layout for Blog Series and Blog Posts.

This ticket is to replace Page Manager & Panels with Layout builder for handling Blog Series and Blog Posts.

## Subtasks
- [ ] Remove Page Manager and Panels from any dependencies. (But leave in composer as the code needs to be there so it will not break.)
   1. Remove the configs from the repo:
       * cgov_blog/config/install/page_manager.page_variant.node_view-panels_variant-blog-post.yml 
       * cgov_blog/config/install/page_manager.page_variant.node_view-panels_variant-blog-series.yml
   2. Update cgov_blog.info.yml and cgov_site.info.yml to remove dependencies on `panels` and `page_manager`.
   3. Add `drupal:layout_builder` as a dependency to cgov_blog.info.yml.
   4. Create cgov_blog update hook to:
       1. Uninstall the `panels` and `page_manager` modules.
       2. Delete the configs:
           * cgov_blog/config/install/page_manager.page_variant.node_view-panels_variant-blog-post.yml 
           * cgov_blog/config/install/page_manager.page_variant.node_view-panels_variant-blog-series.yml
       3. Enable the `layout_builder` module.
- [ ] Setup a new view mode for `node` entities for rendering the primary content of a Node (e.g. the body) in a region of a sublayout. This should go into cgov_core.
   * The view mode details are:
      * **name:**  `lb_primary_content`
      * **label:** "Layout Builder: Primary Content
- [ ] Define all the regions and layouts needed for this conversion.
- [ ] Fix all the blog blocks so they work with Layout Builder. The blocks are pretty brittle and make very strict assumptions about what it being viewed. So you will need a liberal sprinkling of [$this->inPreview](https://www.drupal.org/node/3272267).
- [ ] Update the theme
   * Create a new `node--cgov-blog-post--lb-primary-content.html.twig` template. Copy the contents of `node--cgov-blog-post--full.html.twig` to start. This should basically output the main body content for the page without blocks.
      * The <footer> element should probably get turned into a region. In the layout builder layout we would stack the various components in order.
   * Change the contents of `node--cgov-blog-post--full.html.twig` to be `{{content}}`
   * Modify the `ncids_trans.layouts.yml` file to make 3 new layouts:
      * `cgov_blog_two_col` - this is a layout to replace cgov_blog. It represents 2 columns.  
      * `cgov_blog_post` - this is the layout template to layout the contents of the blog post.
      * `cgov_blog_series`- this is the template to layout the contents of the series.
      * The key thing here is that with layout builder you can nest templates. so `cgov_blog_two_col` will be the wrapper with the right rail and main contents. The `cgov_blog_post` might be the "main contents" and "footer" regions. (two bullets up)
* Configure the full display mode for blogs and blog series to use layout builder. Layout the pages. Poop the configs out.

## Related Links
- [Add visibility control conditions to blocks within Layout Builder](https://www.drupal.org/project/drupal/issues/2916876): This would allow us better control over whether or not blocks should show. We really do not want to output lots of empty HTML if we do not need to.

### LINKED ISSUE #3966: Fix PHPStan issues in cgov_blog
Update cgov_blog in PHPStan

**Modules to be updated**

- [ ]  cgov_blog

**Related blogs tickets**

- [x] #3807 
- [ ] #3710 
- [x] #3804 
- [ ] Others?

Refer to spreadsheet for more info: [https://nih.sharepoint.com/❌/r/sites/NCI-OCPLPlatformSupport/Shared%20Documents/Boundary%20-%20CGDP/Drupal%20Upgrades/Drupal%2010%20Upgrade/Drupal%20bump%20check%20module-errors%20.xlsx?d=w08182fed1b944a28a2e413fb4c2ea679&csf=1&web=1&e=ky5spf](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLPlatformSupport/Shared%20Documents/Boundary%20-%20CGDP/Drupal%20Upgrades/Drupal%2010%20Upgrade/Drupal%20bump%20check%20module-errors%20.xlsx?d=w08182fed1b944a28a2e413fb4c2ea679&csf=1&web=1&e=ky5spf)

### LINKED ISSUE #4054: Cgov Blog Topics URL Translation
### Issue description
When selecting a blog topic from the Categories section and then translating the page to Spanish, the url doesn't translate the current selected topic which effects the highlighting of the term.

### Steps to reproduce the issue

1.  Go to a cgov blog post or blog series page
2. Select any topic in the Categories section (for this example, we will use "Biology of Cancer")
3. Translate the page by clicking "Espanol"
4. Notice how the url still has `topic=biology` instead of `topic=biologia`

### What's the expected result?
- `topic=<spanish-translation>`

### What's the actual result?
- `topic=<english-translation>`

### PR DESCRIPTION
**Pull request by dev-rana-publicis**
- Fixed php stan issues for all cgov_blog blocks. Created an update
  hook that uninstalls page_manager and panels, installs layout_builder
  and contextual links, and deletes the blog post and blog series page
  manager config files.
- Addessed https://github.com/NCIOCPL/cgov-digital-platform/issues/2236 by removing the bad code and deleteing the pathauto file
  in the update hook mentioned above.
- Created a new bug ticket https://github.com/NCIOCPL/cgov-digital-platform/issues/4060 that describes a bug when a pretty url is
  not set on a blog topic taxonomy term.
- After running a `drush features:list packages`, we found that `cgov_file`,
  `cgov_image`, and `cgov_infographic` had changes. This commit addresses the
  config changes for those modules.

Closes https://github.com/NCIOCPL/cgov-digital-platform/issues/2236
Closes https://github.com/NCIOCPL/cgov-digital-platform/issues/3804
Closes https://github.com/NCIOCPL/cgov-digital-platform/issues/3807
Closes https://github.com/NCIOCPL/cgov-digital-platform/issues/3966
Closes #4054

ODE: https://ncigovcdode630.prod.acquia-sites.com

### CODE REVIEW

File: docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Plugin/Block/BlogPager.php [hunk 1]
```diff
@@ -23,7 +23,7 @@ class BlogPager extends BlockBase implements ContainerFactoryPluginInterface {
    *
    * @var \Drupal\cgov_blog\Services\BlogManagerInterface
    */
-  public $blogManager;
+  public $blogManagerTwo;
```
Comment (bryanpizzillo) [inline docroot/profiles/custom/cgov_site/modules/custom/cgov_blog/src/Plugin/Block/BlogPager.php:26]: Meh. This should be $blogManager.

**Review by bryanpizzillo — CHANGES_REQUESTED** [review]
Top priority remove https://github.com/NCIOCPL/cgov-digital-platform/blob/1413a1f0a30e67a035b0b27512991b09fa80c45c/phpcs.xml#L58. 

Lower -- I have noted some instances, but not all. There is only one blog manager again. So everything $blogManagerTwo is going to be confusing in a month.

**Review by blairlearn — APPROVED** [review]
